---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
  labels:
    app: golang
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    nodePort: 30003
    protocol: TCP
  selector:
    app: golang
---
apiVersion: v1
kind: Pod
metadata:
  name: golang-deployment
  labels:
    app: golang
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: golang-container
    image: ther4th/cloud_lab1:golang1
    ports:
    - containerPort: 8080
  - name: service1-container
    image: ther4th/cloud_lab1:service1
    ports:
    - containerPort: 8081
  - name: service2-container
    image: ther4th/cloud_lab1:service2
    ports:
    - containerPort: 8082
  - name: database1-container
    image: ther4th/cloud_lab1:database1
    ports:
    - containerPort: 8083
    volumeMounts:
    - mountPath: /app/data
      name: task-pv-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
